interface EvaluationResult {
  score: string | number;
  overview: string;
  evaluationId?: string | number;
}

interface UserData {
  name: string;
  email: string;
  visaType: string;
}

// Get user data from session storage with fallbacks
export const getUserDataFromStorage = (): UserData => {
  try {
    const storedUserData = sessionStorage.getItem('userData');
    if (storedUserData) {
      const userData = JSON.parse(storedUserData);
      return {
        name: userData.name || 'Unknown',
        email: userData.email || 'not-provided@example.com',
        visaType: userData.visaType || 'Not specified'
      };
    }
  } catch (error) {
    console.error('Error parsing user data from storage:', error);
  }

  return {
    name: 'Unknown',
    email: 'not-provided@example.com',
    visaType: 'Not specified'
  };
};

// Parse overview text and create structured sections
const parseOverviewText = (overview: string) => {
  const sections: string[] = [];
  const lines = overview.split('\n').filter(line => line.trim());
  
  let currentSection = '';
  
  for (const line of lines) {
    const trimmedLine = line.trim();
    
    // Check if it's a section header (contains score pattern like "15/25" or "(15/25)")
    if (trimmedLine.match(/\([0-9]+\/[0-9]+\)|[0-9]+\/[0-9]+/)) {
      // Save previous section if it exists
      if (currentSection) {
        sections.push(currentSection.trim());
      }
      // Start new section
      currentSection = `\n${trimmedLine}\n${'-'.repeat(trimmedLine.length)}\n`;
    } else if (trimmedLine.startsWith('*') || trimmedLine.startsWith('-') || trimmedLine.startsWith('•')) {
      // It's a bullet point
      currentSection += `  ${trimmedLine}\n`;
    } else if (trimmedLine.toLowerCase().includes('you have:') || trimmedLine.toLowerCase().includes('you need:')) {
      // It's a subsection header
      currentSection += `\n${trimmedLine}\n`;
    } else if (trimmedLine) {
      // Regular text
      currentSection += `${trimmedLine}\n`;
    }
  }
  
  // Add the last section
  if (currentSection) {
    sections.push(currentSection.trim());
  }
  
  return sections;
};

export const generateEvaluationText = (evaluationResult: EvaluationResult, userData: UserData): void => {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  const score = typeof evaluationResult.score === 'string' 
    ? evaluationResult.score 
    : `${evaluationResult.score}%`;

  // Parse the overview into structured sections
  const sections = parseOverviewText(evaluationResult.overview);

  // Create the text content
  const textContent = `
SHERROD SPORTS VISAS - EVALUATION REPORT
========================================

Generated on: ${currentDate}

EVALUATION SCORE
---------------
Overall Success Probability: ${score}

DETAILED EVALUATION OVERVIEW
===========================

${sections.map(section => section).join('\n\n')}

DISCLAIMER
==========
This evaluation is based on the information provided and general visa requirements. 
Results are estimates and actual outcomes may vary. For official guidance, consult 
with immigration authorities or qualified legal professionals.

Generated by Sherrod Sports Visas Assessment Tool
Contact: info@sherrodsportsvisas.com
`.trim();

  // Create and download the file
  const element = document.createElement('a');
  const file = new Blob([textContent], { type: 'text/plain' });
  element.href = URL.createObjectURL(file);
  element.download = `visa-evaluation-${userData.name.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
  
  // Clean up the URL
  URL.revokeObjectURL(element.href);
};