// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugrlnoneetxtkcgkkeye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVncmxub25lZXR4dGtjZ2trZXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDA2OTksImV4cCI6MjA2MDIxNjY5OX0.toF_v_5m-WN7vckQrMGEHAZr-mJbhjEcBU2RkT3J0kk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);